/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    fontFamily: {
      sans: ['Inter', 'Helvetica', 'Arial', 'sans-serif'],
      mono: ['Roboto Mono', 'monospace'],
    },
    borderRadius: {
      'none': '0',
      'sm': '2px',
      DEFAULT: '2px',
      'md': '2px',
      'lg': '2px',
      'xl': '2px',
      '2xl': '2px',
      '3xl': '2px',
      'full': '9999px',
    },
    extend: {
      colors: {
        'g': {
          'canvas':    'rgb(var(--g-canvas) / <alpha-value>)',
          'primary':   'rgb(var(--g-primary) / <alpha-value>)',
          'secondary': 'rgb(var(--g-secondary) / <alpha-value>)',
          'elevated':  'rgb(var(--g-elevated) / <alpha-value>)',
          'text':           'rgb(var(--g-text-primary) / <alpha-value>)',
          'text-secondary': 'var(--g-text-secondary)',
          'text-disabled':  'var(--g-text-disabled)',
          'text-link':      'rgb(var(--g-text-link) / <alpha-value>)',
          'border-weak':    'var(--g-border-weak)',
          'border-medium':  'var(--g-border-medium)',
          'border-strong':  'var(--g-border-strong)',
          'accent-main':'rgb(var(--g-accent-main) / <alpha-value>)',
          'accent-text':'rgb(var(--g-accent-text) / <alpha-value>)',
          'blue-main':  'rgb(var(--g-blue-main) / <alpha-value>)',
          'blue-text':  'rgb(var(--g-blue-text) / <alpha-value>)',
          'red-main':   'rgb(var(--g-red-main) / <alpha-value>)',
          'red-text':   'rgb(var(--g-red-text) / <alpha-value>)',
          'green-main': 'rgb(var(--g-green-main) / <alpha-value>)',
          'green-text': 'rgb(var(--g-green-text) / <alpha-value>)',
          'orange-main':'rgb(var(--g-orange-main) / <alpha-value>)',
          'orange-text':'rgb(var(--g-orange-text) / <alpha-value>)',
          'yellow-main':'rgb(var(--g-yellow-main) / <alpha-value>)',
          'yellow-text':'rgb(var(--g-yellow-text) / <alpha-value>)',
          'purple-main':'rgb(var(--g-purple-main) / <alpha-value>)',
          'purple-text':'rgb(var(--g-purple-text) / <alpha-value>)',
          'hover':    'var(--g-action-hover)',
          'selected': 'var(--g-action-selected)',
          'focus':    'var(--g-action-focus)',
        },
      },
      boxShadow: {
        'z1': 'var(--g-shadow-z1)',
        'z2': 'var(--g-shadow-z2)',
        'z3': 'var(--g-shadow-z3)',
      },
    },
  },
  plugins: [],
};
